version: '3'
services:
  app:
    build: './docker/go'
    ports: [ '80:8080' ]
    volumes: [ '.:/opt' ]
  mysql:
    image: 'mysql:8'
    ports: [ '3306:3306' ]
    environment:
      MYSQL_DATABASE: 'api'
      MYSQL_ROOT_PASSWORD: 'password'